updated ci workflow

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -23,9 +23,9 @@ jobs:
       - name: Static code Analysis
         run: npm run lint
 
-      - name: Build project
-        run: |
-          npm start || echo "Error: no test specified\" && exit 1"
+      #- name: Build project
+      #  run: |
+      #    npm start || echo "Error: no test specified\" && exit 1"
 
       - name: Build Docker Image
         run: |
