update ci workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,50 +1,55 @@
-securepassword123name: Deploy Node.js App
+name: Deploy Node.js App
 
 on:
   push:
-    branches:
-      - main
+    branches: [ main ]
 
 jobs:
   build-deploy:
+    name: Unit testing
     runs-on: ubuntu-latest
 
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
+      
+      - name: Set Short SHA
+        run: |
+          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
-
-      - name: Login to GHCR
-        uses: docker/login-action@v2
+      - name: Setup Node.ls
+        uses: actions/setup-node@v4
         with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
+          node-version: '18'
+          cache: 'npm'
 
-      - name: Build and Push Docker Image
-        uses: docker/build-push-action@v5
-        with:
-          context: .
-          file: ./Dockerfile
-          push: true
-          tags: ghcr.io/${{ github.repository }}:latest
+      - name: Install dependencies
+        run: npm ci
 
-      - name: Deploy to Remote Server via SSH
-        uses: appleboy/ssh-action@master
+      - name: Static code Analysis
+        run: npm run lint
+
+      - name: Build project
+        run: npm run build || echo "Error: no test specified\" && exit 1"
+
+      - name: Build Docker Image
+        run: |
+          docker build -t mosesade/nodejs-service:${{ env.SHORT_SHA }} .
+
+      - name: Security scan of Image
+        uses: aquasecurity/trivy-action@master
         with:
-          host: ${{ secrets.SERVER_IP }}
-          username: ${{ secrets.SERVER_USER }}
-          password: ${{ secrets.SERVER_PASSWORD }}
-          port: 22
-          script: |
-            cd /home/${{ secrets.SERVER_USER }} || exit
-            docker pull ghcr.io/${{ github.repository }}:latest
-            docker stop node-app || true
-            docker rm node-app || true
-            docker run -d -p 3000:3000 --name node-app \
-              -e USERNAME=${{ secrets.DOCKER_USERNAME }} \
-              -e PASSWORD=${{ secrets.DOCKER_PASSWORD }} \
-              -e SECRET_MESSAGE=${{ secrets.SECRET_MESSAGE }} \
-              ghcr.io/${{ github.repository }}:latest
+          image-ref: mosesade/nodejs-service:${{ env.SHORT_SHA }}
+          format: 'table'
+          exit-code: '0'
+          ignore-unfixed: true
+          vuln-type: 'os,library'
+          severity: 'CRITICAL,HIGH'
+
+      - name: Login to DockerHub
+        run: |
+          echo echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
+
+      - name: Push Image to DockerHub
+        run: |
+          docker push mosesade/nodejs-service:${{ env.SHORT_SHA }}
