update ci workflow

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -30,7 +30,8 @@ jobs:
         run: npm run lint
 
       - name: Build project
-        run: npm run build || echo "Error: no test specified\" && exit 1"
+        run: |
+          node server.js || echo "Error: no test specified\" && exit 1"
 
       - name: Build Docker Image
         run: |
